### ISSUE TITLE
Add a 'Control Panel' button for going back to /hub/home

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-remote#183] opened 2016-07-27 16:04 UTC
When the remoteappmanager is running, /hub/home looks like this:
![screenshot from 2016-07-27 17 03 01](https://cloud.githubusercontent.com/assets/3673984/17182607/ff8f13c4-541b-11e6-81a5-8b607320320a.png)

It would be convenient to be able to access the page with a button/link.

**Comment by itziakos** [comment] 2016-08-05 13:25
Is this visible by all users?

**Comment by stefanoborini** [comment] 2016-10-04 10:44
It is unclear if the button should be from /user/username to /hub/home or vice-versa. 

In any case...The problem is that the response is from jupyterhub, not us. 
I don't see the benefit in adding either. For all purposes, that page makes no sense to our approach. It's a vestige of the fact that we are based on jupyterhub, which can't be removed/modified without hacking jupyterhub itself for little benefit, or would show the user a feature that is pretty much pointless.

Closing.

**Closed by stefanoborini** 2016-10-04 10:44 UTC

**Comment by kitchoi** [comment] 2016-10-04 11:08
The "My Server" button in /hub/home goes to /user/username
The issue is about adding a button in /user/username to go to /hub/home.

The "Stop My Server" calls spawner.stop and is useful to for getting a clean restart.  To me it is always useful to have a way to restart for unforeseen problems.

**Comment by itziakos** [comment] 2016-10-04 13:42
From the discussion it is not clear to me which server is restarted JupyterHub or simphonyremoteapp?

**Comment by kitchoi** [comment] 2016-10-04 13:43
`Server` refers to the per-user process started by the spawner.

**Comment by itziakos** [comment] 2016-10-04 13:58
Ok, so there is the capability of restarting the spawned process simponyremoteapp that is started for each user. And the suggestion is to provide a similar button  in the simphony-remote-app ui that will tell the jupyter hub server to restart the spawned server process:

- Is this equivalent to log out and log in?
- I can see why it might be important when the spawned process is an ipython notebook server which has a large memory footprint and one would like to restart with a clean slate (especially during debugging.  However, in our case the spawned per user server is very lightweight does it really make sense to restart it?
- The only use case I can think of is the case where the actual code for the simphony remote app has been updated and restarting the server would allow for the new changes to become visible. But this usecase is a little far in the future and depends on the how we decide to perform the system upgrades.

Nevertheless just for debugging purposes it is good to know that one can restart the remote app server live. I would not think that it is necessary to be more prominent at this time.

**Comment by kitchoi** [comment] 2016-10-04 16:32
> Is this equivalent to log out and log in

No.

I just had a closer look at this.  I believe the 'Stop My Server' calls this in jupyterhub https://github.com/jupyterhub/jupyterhub/blob/ad93af8cc85323d417e18791a30728d21d67c12b/jupyterhub/user.py#L291
So it also modifies content in the sqlite database managed by jupyterhub and iit also invalidates api tokens, which make sense if one thinks their tokens are compromised and wants to refresh.
That leads me to wonder if we should invalidate tokens that have been passed onto started containers or kill the started containers when the spawner is stopped (currently we don't clean up containers)
